### ISSUE TITLE
"passive" location provider requires ACCESS_FINE_LOCATION permission.

### ISSUE THREAD

**Issue by ojacquemart** [ojacquemart/vlilleChecker#115]
A bug still present in the latest android versions (7 - 8):

```
java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
	at android.os.Parcel.readException(Parcel.java:1665)
	at android.os.Parcel.readException(Parcel.java:1618)
	at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:725)
	at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1225)
	at com.vlille.checker.ui.osm.location.LocationManagerWrapper.getCurrentLocation(LocationManagerWrapper.java:1064)
	at com.vlille.checker.ui.osm.MapView.drawLocationCircle(MapView.java:3037)
	at com.vlille.checker.ui.osm.MapView.updateLocationCircle(MapView.java:144)
	at com.vlille.checker.ui.fragment.MapFragment$1.onClick(MapFragment.java:163)
	at android.view.View.performClick(View.java:5646)
	at android.view.View$PerformClick.run(View.java:22459)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by ojacquemart** [comment]
Should not be reproductible thanks to https://github.com/ojacquemart/vlilleChecker/commit/8c56e7aa1e609394a554715a4b3da1362031055d
