### ISSUE TITLE
Logs error during stations update

### ISSUE THREAD

**Issue by ojacquemart** [ojacquemart/vlilleChecker#91]
Insert fails with existing station id:
```
3641-3659/com.vlille.checker I/DBUpdater﹕ New stations 7
3641-3659/com.vlille.checker E/SQLiteLog﹕ (1555) abort at 31 in [INSERT INTO station(adress,latitudeE6,longitude,outOfService,ordinal,attachs,cbPaiement,suggest_text_1,bikes,latitude,starred,_id,longitudeE6,lastUpdate) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)]:
3641-3659/com.vlille.checker D/StationEntityManager﹕ Error during insert
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: station._id (code 1555)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
            at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1367)
            at com.vlille.checker.db.StationEntityManager.create(StationEntityManager.java:42)
            at com.vlille.checker.db.StationEntityManager.create(StationEntityManager.java:15)
            at org.droidparts.persist.sql.AbstractEntityManager$1.call(AbstractEntityManager.java:111)
            at org.droidparts.persist.sql.AbstractEntityManager$1.call(AbstractEntityManager.java:102)
            at org.droidparts.inner.PersistUtils.executeInTransaction(PersistUtils.java:155)
            at org.droidparts.persist.sql.AbstractEntityManager.executeInTransaction(AbstractEntityManager.java:148)
            at org.droidparts.persist.sql.AbstractEntityManager.cud(AbstractEntityManager.java:127)
            at org.droidparts.persist.sql.AbstractEntityManager.create(AbstractEntityManager.java:90)
            at com.vlille.checker.db.DBUpdater.update(DBUpdater.java:33)
            at com.vlille.checker.ui.async.DBUpdaterAsyncTask.doInBackground(DBUpdaterAsyncTask.java:32)
            at com.vlille.checker.ui.async.DBUpdaterAsyncTask.doInBackground(DBUpdaterAsyncTask.java:12)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by ojacquemart** [comment]
Fixed in 4.1.0
